prometheus-node-exporter:
 enabled: false
kube-state-metrics:
 enabled: false
alertmanager:
 enabled: true 
 persistence:
   enabled: false
 ingress:
   enabled: true
   className: nginx
   hosts:
     - host: group-3-alertmanager.sctp-sandbox.com
       paths:
         - path: /
           pathType: ImplementationSpecific
   annotations:
     external-dns.alpha.kubernetes.io/hostname: "group-3-alertmanager.sctp-sandbox.com"

serverFiles:
 prometheus.yml:
   scrape_configs:
     - job_name: prometheus
       static_configs:
         - targets:
           - localhost:9090
     - job_name: node-exporter
       static_configs:
         - targets:
           - kube-prometheus-stack-prometheus-node-exporter.monitoring:9100
     - job_name: nginx
       static_configs:
         - targets:
           - ingress-nginx-controller-metrics.ingress-nginx:10254
server:
 persistentVolume:
   enabled: false
 ingress:
   enabled: true
   ingressClassName: nginx
   hosts:
     - group-3-prom.sctp-sandbox.com
 annotations:
   external-dns.alpha.kubernetes.io/hostname: "group-3-prom.sctp-sandbox.com"
